config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :users, :member => {:update_friends => :put} do |users|
    users.resources :friendships
  end

  map.feed '/feed.rss', :controller => "feeds", :action => "index", :format => "rss"
  
  map.resource :user_session
  map.root :controller => "user_sessions", :action => "new"
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Using Authlogic. See write-up for why chosen of Restful Authentication
  acts_as_authentic # for options see documentation: Authlogic::ORMAdapters::ActiveRecordAdapter::ActsAsAuthentic::Config
  
  # Using Paperclip to aid in file storage
  has_attached_file :photo
  
  # Need to overide the defaults of has_and_belongs_to_many so that I can specify a many to many relationship using
  # the same table on both sides of the relationship.
  has_and_belongs_to_many :friends, :join_table => "friendships", :association_foreign_key => "friend_id", :class_name => "User"
  
  # For now, users have just one address. This may change in the future.
  has_one :address
  
  # Helper function to return the cached geo-coordinates in an array
  def geo_coords
    if address && address.longitude && address.latitude
      [address.latitude, address.longitude]
    end
  end
  
  # Helper function to constuct a user's full name
  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/controllers/friendships_controller.rb
# This coordinates the ability for user to designate which other users are his "friends"
class FriendshipsController < ApplicationController

  # GET /users/1/friendships
  def index
    # Find the selected (often current, unless being done by an admin) user
    @user = User.find(params[:user_id])
    
    # Find all users, but removing the selected user (can't be a friend of yourself - wouldn't make sense)
    @users = User.find(:all) - [@user]
    
    # A list of your friends for the view to render
    @friends = @user.friends

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<%# We can safely assume friends are on a first name basis here %>
<h1>Friends of <%= @user.first_name %></h1>

<% form_tag update_friends_user_path(@user), :method => :put do %>
	<%# Oh oh, un-checking a checkbox isn't handled gracefully, submitting the array of current values to help %>
	<%= hidden_field_tag "user[friend_ids][]", "" %>
	<table>
		<% if @users.size == 0 %>
			<tr><td>Sorry, there are no other users in the system for you to select as friends. Please invite your buddies to join.</td></tr>
		<% else %>
	 	    <tr>
		      <th>Friend?</th>
		      <th>First name</th>
		      <th>Last name</th>
		      <th>Email</th>
		    </tr>
			<% for user in @users %>
			  <tr>
			    <td><%= check_box_tag "user[friend_ids][]", user.id, @user.friends.include?(user) %></td>
			    <td><%=h user.first_name %></td>
			    <td><%=h user.last_name %></td>
			    <td><%=h user.email %></td>
			    <td><%= link_to 'Show', user %></td>
			  </tr>
			<% end %>
		<% end %>
	</table>

	<%= submit_tag "Save" %><br/>
	<%= link_to 'Back to Address Book', users_path %>
	

<% end %>